### ISSUE TITLE
mongoclient.getDB is deprecated, please use getDatabase

### ISSUE THREAD

**Issue by emichaf** [Ericsson/eiffel-intelligence#38]
Warnings issued during maven build
/src/main/java/com/ericsson/ei/mongodbhandler/MongoDBHandler.java: Some input files use or override a deprecated API

getDB is deprecated, please use getDatabase

**Comment by xmairaa** [comment]
Replaced **deprecated** code to current alternative code, Here is the pull request https://github.com/Ericsson/eiffel-intelligence/pull/63
