### ISSUE TITLE
ERQueryService.java uses unchecked or unsafe operations

### ISSUE THREAD

**Issue by emichaf** [Ericsson/eiffel-intelligence#39]
Warning generated during maven build:

src\main\j
ava\com\ericsson\ei\erqueryservice\ERQueryService.java uses unchecked or unsafe operations

Recompile with -Xlint:unchecked for details

**Comment by xmairaa** [comment]
removed unchecked or unsafe operations in other code also, Here is the pull request   https://github.com/Ericsson/eiffel-intelligence/pull/63
